-- 查询版本
select VERSION();

-- 建表语句
CREATE TABLE `game`
(
    `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '游戏名'
) ENGINE = InnoDB
  CHARACTER SET = utf8
  COLLATE = utf8_general_ci
  ROW_FORMAT = Compact;

-- 关闭自动提交，mysql每次执行一条语句都默认自动提交，去掉自动提交可大大提高批量操作性能
SET autocommit = 0;
INSERT INTO `game`(`name`) VALUES ('空穴');
INSERT INTO `game`(`name`) VALUES ('全面战争传奇：大不列颠王座');
INSERT INTO `game`(`name`) VALUES ('仙剑奇侠传2');
INSERT INTO `game`(`name`) VALUES ('阿提拉：全面战争');
INSERT INTO `game`(`name`) VALUES ('正当防卫1-4');
INSERT INTO `game`(`name`) VALUES ('苍翼默示录：交叉组队战');
INSERT INTO `game`(`name`) VALUES ('羊肚菌：狩猎游戏');
INSERT INTO `game`(`name`) VALUES ('孤岛危机3');
INSERT INTO `game`(`name`) VALUES ('刀剑神域：虚空断章');
INSERT INTO `game`(`name`) VALUES ('狙击手1-3');
INSERT INTO `game`(`name`) VALUES ('鬼武者HD复刻版');
INSERT INTO `game`(`name`) VALUES ('突袭4/3/2/1');
INSERT INTO `game`(`name`) VALUES ('露露亚的工作室：雅兰德的炼金术士4');
INSERT INTO `game`(`name`) VALUES ('网吧模拟器');
INSERT INTO `game`(`name`) VALUES ('战地3/战地风云3/BF3');
INSERT INTO `game`(`name`) VALUES ('口袋妖怪合集/精灵宝可梦合集/PC模拟器版');
INSERT INTO `game`(`name`) VALUES ('使命召唤9');
INSERT INTO `game`(`name`) VALUES ('轩辕剑7');
INSERT INTO `game`(`name`) VALUES ('遗迹：灰烬重生');
INSERT INTO `game`(`name`) VALUES ('逃生1/2 两部');
INSERT INTO `game`(`name`) VALUES ('暗黑破坏神2重制版');
INSERT INTO `game`(`name`) VALUES ('不义联盟2传奇版/单人.多人同屏');
INSERT INTO `game`(`name`) VALUES ('狙击精英：纳粹僵尸部队2');
INSERT INTO `game`(`name`) VALUES ('异星探险家：网络联机版/星球探索者网络联机');
INSERT INTO `game`(`name`) VALUES ('噬血代码');
INSERT INTO `game`(`name`) VALUES ('拳皇14');
INSERT INTO `game`(`name`) VALUES ('极品飞车17：最高通缉 ');
INSERT INTO `game`(`name`) VALUES ('极品飞车11：街道争霸 中文版');
INSERT INTO `game`(`name`) VALUES ('古墓丽影10：崛起/古墓丽影崛起');
INSERT INTO `game`(`name`) VALUES ('英雄无敌2');
INSERT INTO `game`(`name`) VALUES ('流浪汉模拟器/Bum Simulator');
INSERT INTO `game`(`name`) VALUES ('逃离塔科夫');
INSERT INTO `game`(`name`) VALUES ('战地5（战地风云5／BF5＋1）');
INSERT INTO `game`(`name`) VALUES ('浮岛物语');
INSERT INTO `game`(`name`) VALUES ('尘埃3/DiRT 3');
INSERT INTO `game`(`name`) VALUES ('古剑奇谭1');
INSERT INTO `game`(`name`) VALUES ('剑侠情缘单机版合集');
INSERT INTO `game`(`name`) VALUES ('这是我的战争');
INSERT INTO `game`(`name`) VALUES ('合金装备崛起：复仇');
INSERT INTO `game`(`name`) VALUES ('乐高侏罗纪世界');
INSERT INTO `game`(`name`) VALUES ('工业小镇');
INSERT INTO `game`(`name`) VALUES ('极品飞车10：卡本峡谷 英文版');
INSERT INTO `game`(`name`) VALUES ('职业篮球NBA14 NBA2K14');
INSERT INTO `game`(`name`) VALUES ('战地3win10不兼容');
INSERT INTO `game`(`name`) VALUES ('魔兽争霸III魔兽争霸3：冰封王座合集');
INSERT INTO `game`(`name`) VALUES ('轩辕剑6');
INSERT INTO `game`(`name`) VALUES ('鬼泣3');
INSERT INTO `game`(`name`) VALUES ('飞向月球');
INSERT INTO `game`(`name`) VALUES ('英雄无敌1-7');
INSERT INTO `game`(`name`) VALUES ('和班尼特福迪一起攻克难关/掘地求升/罐装的天才');
INSERT INTO `game`(`name`) VALUES ('阿普索夫：诸神终结');
INSERT INTO `game`(`name`) VALUES ('行尸走肉 最终季');
INSERT INTO `game`(`name`) VALUES ('海贼王合集');
INSERT INTO `game`(`name`) VALUES ('斩服少女：异布');
INSERT INTO `game`(`name`) VALUES ('福尔摩斯：恶魔之女');
INSERT INTO `game`(`name`) VALUES ('主播生活模拟器');
INSERT INTO `game`(`name`) VALUES ('暗黑地牢');
INSERT INTO `game`(`name`) VALUES ('古墓丽影6');
INSERT INTO `game`(`name`) VALUES ('亿万僵尸军团');
INSERT INTO `game`(`name`) VALUES ('赤痕/血污：夜之仪式');
INSERT INTO `game`(`name`) VALUES ('极速骑行4');
INSERT INTO `game`(`name`) VALUES ('古剑奇谭2');
INSERT INTO `game`(`name`) VALUES ('碧蓝航线：Crosswave');
INSERT INTO `game`(`name`) VALUES ('黑手党2：最终版/四海兄弟2决定版/四海兄弟II最终版');
INSERT INTO `game`(`name`) VALUES ('乐高霍比特人');
INSERT INTO `game`(`name`) VALUES ('狙击精英4');
INSERT INTO `game`(`name`) VALUES ('求生之路2');
INSERT INTO `game`(`name`) VALUES ('贪婪之秋');
INSERT INTO `game`(`name`) VALUES ('恶灵附身2+1');
INSERT INTO `game`(`name`) VALUES ('孤岛危机3');
INSERT INTO `game`(`name`) VALUES ('傲世苍龙赵云传');
INSERT INTO `game`(`name`) VALUES ('灵魂能力6/刀魂6剑魂6');
INSERT INTO `game`(`name`) VALUES ('使命召唤11');
INSERT INTO `game`(`name`) VALUES ('极品飞车20：复仇');
INSERT INTO `game`(`name`) VALUES ('破坏领主');
INSERT INTO `game`(`name`) VALUES ('如龙：极2/单机.同屏联机');
INSERT INTO `game`(`name`) VALUES ('欧陆风云4');
INSERT INTO `game`(`name`) VALUES ('海商王4');
INSERT INTO `game`(`name`) VALUES ('迸发2');
INSERT INTO `game`(`name`) VALUES ('东京喰种：re CALL to EXIST');
INSERT INTO `game`(`name`) VALUES ('井中生物');
INSERT INTO `game`(`name`) VALUES ('漫威复仇者联盟/Marvel’s Avengers');
INSERT INTO `game`(`name`) VALUES ('孤岛惊魂新曙光');
INSERT INTO `game`(`name`) VALUES ('无双大蛇3：终极版');
INSERT INTO `game`(`name`) VALUES ('轩辕剑4：黑龙舞兮云飞扬');
INSERT INTO `game`(`name`) VALUES ('刺客信条叛变');
INSERT INTO `game`(`name`) VALUES ('模拟人生3');
INSERT INTO `game`(`name`) VALUES ('夕生');
INSERT INTO `game`(`name`) VALUES ('三位一体4：梦魇王子/单机.网络联机');
INSERT INTO `game`(`name`) VALUES ('史诗战争模拟器');
INSERT INTO `game`(`name`) VALUES ('精灵战记');
INSERT INTO `game`(`name`) VALUES ('泰拉瑞亚');
INSERT INTO `game`(`name`) VALUES ('骑马与砍杀2：霸主');
INSERT INTO `game`(`name`) VALUES ('深渊奥德赛');
INSERT INTO `game`(`name`) VALUES ('坎巴拉太空计划');
INSERT INTO `game`(`name`) VALUES ('横扫千星');
INSERT INTO `game`(`name`) VALUES ('火种');
INSERT INTO `game`(`name`) VALUES ('求生之路2/生存之旅2+1/单机.网络联机');
INSERT INTO `game`(`name`) VALUES ('女忍反射：闪乱神乐/忍纾压');
INSERT INTO `game`(`name`) VALUES ('逃生2');
INSERT INTO `game`(`name`) VALUES ('塞尔达传说：荒野之息 旷野之息');
INSERT INTO `game`(`name`) VALUES ('荒无人烟');
INSERT INTO `game`(`name`) VALUES ('刺客信条3＋华盛顿');
INSERT INTO `game`(`name`) VALUES ('生化危机启示录2');
INSERT INTO `game`(`name`) VALUES ('职业篮球NBA16 NBA2K16');
INSERT INTO `game`(`name`) VALUES ('进击!要塞!/进击要塞');
INSERT INTO `game`(`name`) VALUES ('以撒的结合：重生');
INSERT INTO `game`(`name`) VALUES ('轩辕剑外传：穹之扉');
INSERT INTO `game`(`name`) VALUES ('罪印');
INSERT INTO `game`(`name`) VALUES ('黑暗之魂重制版');
INSERT INTO `game`(`name`) VALUES ('炽热熔岩');
INSERT INTO `game`(`name`) VALUES ('死亡细胞');
INSERT INTO `game`(`name`) VALUES ('大佬竞速');
INSERT INTO `game`(`name`) VALUES ('火焰审判');
INSERT INTO `game`(`name`) VALUES ('星际指挥官');
INSERT INTO `game`(`name`) VALUES ('歧路旅人/八方旅人');
INSERT INTO `game`(`name`) VALUES ('这是警察');
INSERT INTO `game`(`name`) VALUES ('羁留');
INSERT INTO `game`(`name`) VALUES ('一拳超人：无名英雄');
INSERT INTO `game`(`name`) VALUES ('激进的搬迁/极限搬迁/极限超载搬家');
INSERT INTO `game`(`name`) VALUES ('曼岛TT摩托车大赛/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('大富翁10');
INSERT INTO `game`(`name`) VALUES ('油管主播的生活');
INSERT INTO `game`(`name`) VALUES ('刺客信条2启示录');
INSERT INTO `game`(`name`) VALUES ('校园默示录');
INSERT INTO `game`(`name`) VALUES ('侠盗猎车手：罪恶都市');
INSERT INTO `game`(`name`) VALUES ('超凡双生/超凡人生');
INSERT INTO `game`(`name`) VALUES ('伟大时代：中世纪');
INSERT INTO `game`(`name`) VALUES ('恐怖黎明');
INSERT INTO `game`(`name`) VALUES ('赛博朋克2077');
INSERT INTO `game`(`name`) VALUES ('刺客信条2');
INSERT INTO `game`(`name`) VALUES ('尘埃拉力赛2.0，送历代下载。');
INSERT INTO `game`(`name`) VALUES ('极品飞车14：热力追踪 英文版');
INSERT INTO `game`(`name`) VALUES ('海底大猎杀');
INSERT INTO `game`(`name`) VALUES ('无人深空');
INSERT INTO `game`(`name`) VALUES ('丧尸围城3');
INSERT INTO `game`(`name`) VALUES ('圣剑传说3：重制版');
INSERT INTO `game`(`name`) VALUES ('GTA5mod可剧情版/侠盗飞车5/侠盗猎车手5');
INSERT INTO `game`(`name`) VALUES ('富甲天下4');
INSERT INTO `game`(`name`) VALUES ('赏金奇兵3');
INSERT INTO `game`(`name`) VALUES ('战锤40K：战争黎明3');
INSERT INTO `game`(`name`) VALUES ('使命召唤6');
INSERT INTO `game`(`name`) VALUES ('古剑奇谭3');
INSERT INTO `game`(`name`) VALUES ('战争机器5/Gears 5');
INSERT INTO `game`(`name`) VALUES ('魔神少女');
INSERT INTO `game`(`name`) VALUES ('皇牌空战7：未知空域');
INSERT INTO `game`(`name`) VALUES ('轩辕剑外传：汉之云');
INSERT INTO `game`(`name`) VALUES ('全面战争：战锤2');
INSERT INTO `game`(`name`) VALUES ('地狱之刃：塞娜的献祭');
INSERT INTO `game`(`name`) VALUES ('南方公园：真理之杖/South Park: The Stick of Truth');
INSERT INTO `game`(`name`) VALUES ('空洞骑士');
INSERT INTO `game`(`name`) VALUES ('狙击精英V2重制版');
INSERT INTO `game`(`name`) VALUES ('真三国无双8');
INSERT INTO `game`(`name`) VALUES ('监狱建筑师');
INSERT INTO `game`(`name`) VALUES ('石油骚动/石油大亨/采油热');
INSERT INTO `game`(`name`) VALUES ('奇迹时代：星陨');
INSERT INTO `game`(`name`) VALUES ('职业自行车队经理2019');
INSERT INTO `game`(`name`) VALUES ('光之子');
INSERT INTO `game`(`name`) VALUES ('S057圣女战旗');
INSERT INTO `game`(`name`) VALUES ('极品飞车合集1-18/20复仇/21热度不含12/13');
INSERT INTO `game`(`name`) VALUES ('终结者：反抗军/抵抗');
INSERT INTO `game`(`name`) VALUES ('辐射4 +3+2+1合集/辐射避难所/新维加斯/钢铁兄');
INSERT INTO `game`(`name`) VALUES ('城市：天际线');
INSERT INTO `game`(`name`) VALUES ('钓鱼模拟世界专业鲈鱼渔具版');
INSERT INTO `game`(`name`) VALUES ('真三国无双7');
INSERT INTO `game`(`name`) VALUES ('狙击手：幽灵战士3');
INSERT INTO `game`(`name`) VALUES ('朝圣者');
INSERT INTO `game`(`name`) VALUES ('乐高指环王');
INSERT INTO `game`(`name`) VALUES ('AI：梦境档案');
INSERT INTO `game`(`name`) VALUES ('狙击精英3');
INSERT INTO `game`(`name`) VALUES ('亨利毕绍普的历史');
INSERT INTO `game`(`name`) VALUES ('料理模拟器/烹饪模拟器');
INSERT INTO `game`(`name`) VALUES ('侍道外传：刀神');
INSERT INTO `game`(`name`) VALUES ('黑手党：最终版/四海兄弟: 最终版');
INSERT INTO `game`(`name`) VALUES ('街头霸王4终极版 v1.05');
INSERT INTO `game`(`name`) VALUES ('龙星的瓦尔尼尔');
INSERT INTO `game`(`name`) VALUES ('地平线：零之曙光');
INSERT INTO `game`(`name`) VALUES ('勇者战机少女/超级海王星');
INSERT INTO `game`(`name`) VALUES ('死或生/生或死6+5');
INSERT INTO `game`(`name`) VALUES ('影子武士');
INSERT INTO `game`(`name`) VALUES ('暗黑破坏神2 ：毁灭之王 V1.14D 20周年版');
INSERT INTO `game`(`name`) VALUES ('火影忍者：究极忍者风暴4');
INSERT INTO `game`(`name`) VALUES ('武装突袭3');
INSERT INTO `game`(`name`) VALUES ('文明5');
INSERT INTO `game`(`name`) VALUES ('GTA5纯净版v1.50/侠盗飞车5/侠盗猎车手5');
INSERT INTO `game`(`name`) VALUES ('黑色未来88');
INSERT INTO `game`(`name`) VALUES ('尼尔：机械纪元');
INSERT INTO `game`(`name`) VALUES ('闪乱神乐爆裂Burst Re：Newal');
INSERT INTO `game`(`name`) VALUES ('模拟火车2019+2020');
INSERT INTO `game`(`name`) VALUES ('少林九武猴');
INSERT INTO `game`(`name`) VALUES ('纸人2+1');
INSERT INTO `game`(`name`) VALUES ('钢铁之狼：混沌XD');
INSERT INTO `game`(`name`) VALUES ('人类：一败涂地');
INSERT INTO `game`(`name`) VALUES ('星球大战绝地：陨落的武士团');
INSERT INTO `game`(`name`) VALUES ('超级果酱/单机.同屏多人.网络联机');
INSERT INTO `game`(`name`) VALUES ('农民模拟器/农民王朝');
INSERT INTO `game`(`name`) VALUES ('传说之下');
INSERT INTO `game`(`name`) VALUES ('只只大冒险');
INSERT INTO `game`(`name`) VALUES ('仙剑奇侠传5');
INSERT INTO `game`(`name`) VALUES ('拳皇13');
INSERT INTO `game`(`name`) VALUES ('奇异人生2 全5章/奇异人生2全章节解锁版');
INSERT INTO `game`(`name`) VALUES ('乐高世界');
INSERT INTO `game`(`name`) VALUES ('使命召唤2');
INSERT INTO `game`(`name`) VALUES ('汤姆克兰西之鹰击长空2/单机.局域网联机');
INSERT INTO `game`(`name`) VALUES ('极乐迪斯科');
INSERT INTO `game`(`name`) VALUES ('武士杰克：时空之战');
INSERT INTO `game`(`name`) VALUES ('战纹/战律/火焰纹章+高级战争');
INSERT INTO `game`(`name`) VALUES ('刺客信条7：起源/刺客信条起源');
INSERT INTO `game`(`name`) VALUES ('口袋妖怪剑盾/精灵宝可梦剑盾');
INSERT INTO `game`(`name`) VALUES ('异星工厂');
INSERT INTO `game`(`name`) VALUES ('NBA2K21/NBA21/2K21');
INSERT INTO `game`(`name`) VALUES ('死亡学校');
INSERT INTO `game`(`name`) VALUES ('龙珠Z：卡卡罗特');
INSERT INTO `game`(`name`) VALUES ('传奇刺客Kal');
INSERT INTO `game`(`name`) VALUES ('小飞蛛');
INSERT INTO `game`(`name`) VALUES ('雷曼传奇');
INSERT INTO `game`(`name`) VALUES ('职业篮球NBA13 NBA2K13');
INSERT INTO `game`(`name`) VALUES ('拿破仑：全面战争');
INSERT INTO `game`(`name`) VALUES ('四海旅人');
INSERT INTO `game`(`name`) VALUES ('第3000次决斗');
INSERT INTO `game`(`name`) VALUES ('赛车计划2');
INSERT INTO `game`(`name`) VALUES ('轩辕剑外传：云之遥');
INSERT INTO `game`(`name`) VALUES ('渡神纪：芬尼斯崛起');
INSERT INTO `game`(`name`) VALUES ('遨游中国2 v1.20稳定版/欧洲模拟卡车2/CTS6');
INSERT INTO `game`(`name`) VALUES ('孤岛危机：重制版');
INSERT INTO `game`(`name`) VALUES ('国际足球大联盟19 FIFA 19');
INSERT INTO `game`(`name`) VALUES ('了不起的修仙模拟器');
INSERT INTO `game`(`name`) VALUES ('王国风云2/十字军之王2');
INSERT INTO `game`(`name`) VALUES ('神界：原罪2');
INSERT INTO `game`(`name`) VALUES ('2020年东京奥运会');
INSERT INTO `game`(`name`) VALUES ('杀手13重制版');
INSERT INTO `game`(`name`) VALUES ('天穗之咲稻姬');
INSERT INTO `game`(`name`) VALUES ('星球大战：前线2/Star Wars Battlefront 2');
INSERT INTO `game`(`name`) VALUES ('WWE2K18-2K20');
INSERT INTO `game`(`name`) VALUES ('女神异闻录4黄金版');
INSERT INTO `game`(`name`) VALUES ('七日杀');
INSERT INTO `game`(`name`) VALUES ('FIFA2019/2018 全系列');
INSERT INTO `game`(`name`) VALUES ('孢子：银河大冒险');
INSERT INTO `game`(`name`) VALUES ('命运/创世 连接');
INSERT INTO `game`(`name`) VALUES ('荣誉勋章：战士2010/及系列');
INSERT INTO `game`(`name`) VALUES ('荣誉勋章之血战太平洋');
INSERT INTO `game`(`name`) VALUES ('生化危机4：终极高清版');
INSERT INTO `game`(`name`) VALUES ('PC微软飞行模拟2020');
INSERT INTO `game`(`name`) VALUES ('英雄无敌1');
INSERT INTO `game`(`name`) VALUES ('幽灵行动：荒野');
INSERT INTO `game`(`name`) VALUES ('双点医院');
INSERT INTO `game`(`name`) VALUES ('战地5，含1.2.3');
INSERT INTO `game`(`name`) VALUES ('信长之野望：大志');
INSERT INTO `game`(`name`) VALUES ('使命召唤8');
INSERT INTO `game`(`name`) VALUES ('最终幻想13-3');
INSERT INTO `game`(`name`) VALUES ('丧尸围城4');
INSERT INTO `game`(`name`) VALUES ('光环4整合士官长致远星');
INSERT INTO `game`(`name`) VALUES ('西部女孩/West Sweety–Fair Lady');
INSERT INTO `game`(`name`) VALUES ('火炬之光3/Torchlight 3');
INSERT INTO `game`(`name`) VALUES ('使命召唤13');
INSERT INTO `game`(`name`) VALUES ('缺氧');
INSERT INTO `game`(`name`) VALUES ('狂怒2');
INSERT INTO `game`(`name`) VALUES ('战斗四驱车/战斗赛车/');
INSERT INTO `game`(`name`) VALUES ('孤胆枪手2');
INSERT INTO `game`(`name`) VALUES ('渎神');
INSERT INTO `game`(`name`) VALUES ('使命召唤10');
INSERT INTO `game`(`name`) VALUES ('核爆RPG：末日余生');
INSERT INTO `game`(`name`) VALUES ('游戏王');
INSERT INTO `game`(`name`) VALUES ('喵斯快跑');
INSERT INTO `game`(`name`) VALUES ('重装机犬/METAL DOGS（别名：金属狗）');
INSERT INTO `game`(`name`) VALUES ('我的世界');
INSERT INTO `game`(`name`) VALUES ('幽灵行者');
INSERT INTO `game`(`name`) VALUES ('吸血鬼');
INSERT INTO `game`(`name`) VALUES ('辐射3');
INSERT INTO `game`(`name`) VALUES ('寂静岭5：归途');
INSERT INTO `game`(`name`) VALUES ('无业工作');
INSERT INTO `game`(`name`) VALUES ('生化危机：浣熊市行动');
INSERT INTO `game`(`name`) VALUES ('实况足球2021');
INSERT INTO `game`(`name`) VALUES ('爱丽丝：疯狂回归');
INSERT INTO `game`(`name`) VALUES ('三国群英传1-7');
INSERT INTO `game`(`name`) VALUES ('请出示证件');
INSERT INTO `game`(`name`) VALUES ('杀手2');
INSERT INTO `game`(`name`) VALUES ('杀戮尖塔');
INSERT INTO `game`(`name`) VALUES ('港诡实录/港鬼实录');
INSERT INTO `game`(`name`) VALUES ('伊苏8：达娜的安魂曲');
INSERT INTO `game`(`name`) VALUES ('GTA4侠盗猎车4自由城纯净版');
INSERT INTO `game`(`name`) VALUES ('黑道圣徒系列2+3+4');
INSERT INTO `game`(`name`) VALUES ('剑士');
INSERT INTO `game`(`name`) VALUES ('瘟疫公司：进化');
INSERT INTO `game`(`name`) VALUES ('街头霸王5：冠军版/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('木筏生存/单机版/木筏求生/船长漂流记');
INSERT INTO `game`(`name`) VALUES ('编程模拟器');
INSERT INTO `game`(`name`) VALUES ('死神菲利克斯');
INSERT INTO `game`(`name`) VALUES ('Arise：一个平凡的故事');
INSERT INTO `game`(`name`) VALUES ('极品飞车9：最高通辑');
INSERT INTO `game`(`name`) VALUES ('海腹川背/同屏多人.网络联机');
INSERT INTO `game`(`name`) VALUES ('窃贼模拟器/小偷模拟');
INSERT INTO `game`(`name`) VALUES ('无主之地3');
INSERT INTO `game`(`name`) VALUES ('寒霜朋克/冰汽时代');
INSERT INTO `game`(`name`) VALUES ('刺客信条：英灵殿');
INSERT INTO `game`(`name`) VALUES ('龙珠：超宇宙2');
INSERT INTO `game`(`name`) VALUES ('毁灭全人类：重制版');
INSERT INTO `game`(`name`) VALUES ('合金装备5：幻痛');
INSERT INTO `game`(`name`) VALUES ('乐高 蝙蝠侠2');
INSERT INTO `game`(`name`) VALUES ('逃出生天');
INSERT INTO `game`(`name`) VALUES ('创世纪：阿尔法一号/起源阿尔法一号');
INSERT INTO `game`(`name`) VALUES ('火影忍者终极忍者风暴革命');
INSERT INTO `game`(`name`) VALUES ('梦幻模拟战2');
INSERT INTO `game`(`name`) VALUES ('太吾绘卷/电脑小游戏');
INSERT INTO `game`(`name`) VALUES ('INSIDE/内部/地狱边境续作:囚禁');
INSERT INTO `game`(`name`) VALUES ('仙剑奇侠传6');
INSERT INTO `game`(`name`) VALUES ('双人成行');
INSERT INTO `game`(`name`) VALUES ('职业篮球NBA19 NBA2K19');
INSERT INTO `game`(`name`) VALUES ('过山车之星');
INSERT INTO `game`(`name`) VALUES ('最终幻想15');
INSERT INTO `game`(`name`) VALUES ('植物大战僵尸合集');
INSERT INTO `game`(`name`) VALUES ('马赛克');
INSERT INTO `game`(`name`) VALUES ('惊恐航海');
INSERT INTO `game`(`name`) VALUES ('分手装修/Tools Up!/单机.多人同屏');
INSERT INTO `game`(`name`) VALUES ('FIFA19 (46G) /18/17/15/14/13/12/11/10国际足球大联盟全家');
INSERT INTO `game`(`name`) VALUES ('战地2硬仗');
INSERT INTO `game`(`name`) VALUES ('三位一体3：权力的神器/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('视界线：前沿');
INSERT INTO `game`(`name`) VALUES ('孤岛惊魂4');
INSERT INTO `game`(`name`) VALUES ('手掌模拟器：生存/网络联机');
INSERT INTO `game`(`name`) VALUES ('消逝的光芒：信徒增强版/单机版 (31.3G)');
INSERT INTO `game`(`name`) VALUES ('世界摩托大奖赛21/摩托GP21');
INSERT INTO `game`(`name`) VALUES ('暗黑破坏神3：夺魂之镰单机');
INSERT INTO `game`(`name`) VALUES ('龙腾世纪3：审判');
INSERT INTO `game`(`name`) VALUES ('上古卷轴5：天际');
INSERT INTO `game`(`name`) VALUES ('国际足球大联盟15 FIFA 15');
INSERT INTO `game`(`name`) VALUES ('闪乱神乐：桃色弹珠');
INSERT INTO `game`(`name`) VALUES ('星球大战：前线2/Star Wars Battlefront 2');
INSERT INTO `game`(`name`) VALUES ('小小噩梦2/小小梦魇2');
INSERT INTO `game`(`name`) VALUES ('僵尸世界大战');
INSERT INTO `game`(`name`) VALUES ('帕尔米拉孤儿院');
INSERT INTO `game`(`name`) VALUES ('全面战争传奇：特洛伊');
INSERT INTO `game`(`name`) VALUES ('茶杯头');
INSERT INTO `game`(`name`) VALUES ('中国式家长');
INSERT INTO `game`(`name`) VALUES ('孤岛惊魂新曙光+系列（包含1-5/原始杀戮）');
INSERT INTO `game`(`name`) VALUES ('超级马里奥制造');
INSERT INTO `game`(`name`) VALUES ('生化危机2重置版');
INSERT INTO `game`(`name`) VALUES ('细胞分裂6');
INSERT INTO `game`(`name`) VALUES ('生化奇兵3：无限/2/1');
INSERT INTO `game`(`name`) VALUES ('勇敢者游戏');
INSERT INTO `game`(`name`) VALUES ('实况足球2018/2019');
INSERT INTO `game`(`name`) VALUES ('灾厄逆刃/天灾降临/天灾使者');
INSERT INTO `game`(`name`) VALUES ('三国志14威力加强版');
INSERT INTO `game`(`name`) VALUES ('观测号/观察号');
INSERT INTO `game`(`name`) VALUES ('毁灭战士：永恒');
INSERT INTO `game`(`name`) VALUES ('超级机器人大战X');
INSERT INTO `game`(`name`) VALUES ('三国志13威力加强版');
INSERT INTO `game`(`name`) VALUES ('帝国时代3：决定版');
INSERT INTO `game`(`name`) VALUES ('刺客信条4黑旗＋自由呐喊');
INSERT INTO `game`(`name`) VALUES ('帝国时代3');
INSERT INTO `game`(`name`) VALUES ('曼岛TT赛事：边缘竞速2/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('使命召唤6重制版');
INSERT INTO `game`(`name`) VALUES ('机械迷城');
INSERT INTO `game`(`name`) VALUES ('仙剑奇侠传4');
INSERT INTO `game`(`name`) VALUES ('俄罗斯方块效应/Tetris Effect');
INSERT INTO `game`(`name`) VALUES ('刺客信条奥德赛');
INSERT INTO `game`(`name`) VALUES ('铁拳7');
INSERT INTO `game`(`name`) VALUES ('幕府将军2：全面战争');
INSERT INTO `game`(`name`) VALUES ('古墓丽影：暗影/克劳馥版/历代1到11合集');
INSERT INTO `game`(`name`) VALUES ('英雄萨姆4');
INSERT INTO `game`(`name`) VALUES ('层层恐惧2');
INSERT INTO `game`(`name`) VALUES ('杀出重围：人类革命');
INSERT INTO `game`(`name`) VALUES ('职业篮球NBA17 NBA2K17');
INSERT INTO `game`(`name`) VALUES ('改变：无家可归生存');
INSERT INTO `game`(`name`) VALUES ('地铁：最后的曙光 重置版');
INSERT INTO `game`(`name`) VALUES ('极限竞速：地平线4');
INSERT INTO `game`(`name`) VALUES ('至暗之光');
INSERT INTO `game`(`name`) VALUES ('城堡破坏者');
INSERT INTO `game`(`name`) VALUES ('星球大战：战争前线2/星际大战 战场前线2');
INSERT INTO `game`(`name`) VALUES ('牧场物语：希望之光');
INSERT INTO `game`(`name`) VALUES ('行尸走肉：超杀');
INSERT INTO `game`(`name`) VALUES ('仙剑奇侠传合集');
INSERT INTO `game`(`name`) VALUES ('WWE2K20');
INSERT INTO `game`(`name`) VALUES ('使命召唤1代到14合集');
INSERT INTO `game`(`name`) VALUES ('毒枭：卡特尔崛起');
INSERT INTO `game`(`name`) VALUES ('美丽水世界：零度之下/深海迷航零度之下');
INSERT INTO `game`(`name`) VALUES ('疯狂麦克斯');
INSERT INTO `game`(`name`) VALUES ('迷失森林 局域网联机版/支持单机');
INSERT INTO `game`(`name`) VALUES ('生死大乱斗/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('轩辕剑5：一剑凌云山海情');
INSERT INTO `game`(`name`) VALUES ('荒岛求生');
INSERT INTO `game`(`name`) VALUES ('Stela');
INSERT INTO `game`(`name`) VALUES ('火影忍者博人传：忍者先锋');
INSERT INTO `game`(`name`) VALUES ('生化危机6特别版');
INSERT INTO `game`(`name`) VALUES ('恶魔便便的进攻');
INSERT INTO `game`(`name`) VALUES ('小偷模拟器/窃贼模拟器/盗贼模拟');
INSERT INTO `game`(`name`) VALUES ('战锤40K：格雷迪厄斯 遗迹之战');
INSERT INTO `game`(`name`) VALUES ('乐高加勒比海盗 亡灵宝藏');
INSERT INTO `game`(`name`) VALUES ('瓦尔法瑞斯');
INSERT INTO `game`(`name`) VALUES ('德军总部2：新巨像');
INSERT INTO `game`(`name`) VALUES ('细胞迷途');
INSERT INTO `game`(`name`) VALUES ('异形：火力小队精英/Aliens: Fireteam Elite');
INSERT INTO `game`(`name`) VALUES ('打造世界：单机版/创造世界');
INSERT INTO `game`(`name`) VALUES ('汽车修理工模拟2018');
INSERT INTO `game`(`name`) VALUES ('碧蓝幻想Versus/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('中土世界：战争之影');
INSERT INTO `game`(`name`) VALUES ('海贼王：世界探索者');
INSERT INTO `game`(`name`) VALUES ('刺客信条编年史中国');
INSERT INTO `game`(`name`) VALUES ('使命召唤7【可单人/联机 僵尸模式】');
INSERT INTO `game`(`name`) VALUES ('变形法则');
INSERT INTO `game`(`name`) VALUES ('畸战求生/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('战神系列 1-2 PS2模拟版');
INSERT INTO `game`(`name`) VALUES ('符文2');
INSERT INTO `game`(`name`) VALUES ('信长之野望创造：战国立志传');
INSERT INTO `game`(`name`) VALUES ('火影忍者合集');
INSERT INTO `game`(`name`) VALUES ('哆啦A梦：大雄的牧场物语');
INSERT INTO `game`(`name`) VALUES ('极品飞车18：宿敌');
INSERT INTO `game`(`name`) VALUES ('瘟疫传说：无罪');
INSERT INTO `game`(`name`) VALUES ('罗马MOD隋唐');
INSERT INTO `game`(`name`) VALUES ('富甲天下5');
INSERT INTO `game`(`name`) VALUES ('金庸群侠传');
INSERT INTO `game`(`name`) VALUES ('生化危机5：黄金版');
INSERT INTO `game`(`name`) VALUES ('古墓丽影8');
INSERT INTO `game`(`name`) VALUES ('失忆症：重生/Amnesia: Rebirth');
INSERT INTO `game`(`name`) VALUES ('勇者斗恶龙：创世小玩家2');
INSERT INTO `game`(`name`) VALUES ('使命召唤7');
INSERT INTO `game`(`name`) VALUES ('狂超杀：行尸走肉/单机.网络联机');
INSERT INTO `game`(`name`) VALUES ('进击的巨人2+1');
INSERT INTO `game`(`name`) VALUES ('口袋妖怪/精灵宝可梦：究极之日究极之月');
INSERT INTO `game`(`name`) VALUES ('地球防卫军5');
INSERT INTO `game`(`name`) VALUES ('侠客风云传');
INSERT INTO `game`(`name`) VALUES ('极品飞车7');
INSERT INTO `game`(`name`) VALUES ('乞丐模拟器');
INSERT INTO `game`(`name`) VALUES ('孤岛危机弹头');
INSERT INTO `game`(`name`) VALUES ('武林志：风云再起');
INSERT INTO `game`(`name`) VALUES ('废墟战旗/废墟的旗帜');
INSERT INTO `game`(`name`) VALUES ('博德之门3');
INSERT INTO `game`(`name`) VALUES ('部落与弯刀');
INSERT INTO `game`(`name`) VALUES ('三国志7-14');
INSERT INTO `game`(`name`) VALUES ('​暴雨/Heavy Rain ');
INSERT INTO `game`(`name`) VALUES ('黑暗之魂1');
INSERT INTO `game`(`name`) VALUES ('帝国时代1');
INSERT INTO `game`(`name`) VALUES ('地球防卫军：铁雨');
INSERT INTO `game`(`name`) VALUES ('使命召唤12');
INSERT INTO `game`(`name`) VALUES ('狙击精英2 重置版');
INSERT INTO `game`(`name`) VALUES ('往日不再/Days Gone');
INSERT INTO `game`(`name`) VALUES ('行尸走肉第二季');
INSERT INTO `game`(`name`) VALUES ('王国风云3/十字军之王3');
INSERT INTO `game`(`name`) VALUES ('辐射1');
INSERT INTO `game`(`name`) VALUES ('刺客信条4 俄罗斯');
INSERT INTO `game`(`name`) VALUES ('世界摩托大奖赛20');
INSERT INTO `game`(`name`) VALUES ('行尸走肉：终极系列合集/7部合集');
INSERT INTO `game`(`name`) VALUES ('归于沉寂');
INSERT INTO `game`(`name`) VALUES ('禁闭求生/Grounded');
INSERT INTO `game`(`name`) VALUES ('远征猎人/使命猎人');
INSERT INTO `game`(`name`) VALUES ('松树');
INSERT INTO `game`(`name`) VALUES ('使命召唤5');
INSERT INTO `game`(`name`) VALUES ('赛道大师/边境制造者');
INSERT INTO `game`(`name`) VALUES ('旋转轮胎：泥泞奔驰');
INSERT INTO `game`(`name`) VALUES ('沉没之城');
INSERT INTO `game`(`name`) VALUES ('勇者斗恶龙11');
INSERT INTO `game`(`name`) VALUES ('队长小翼：新秀崛起/足球小将新秀崛起');
INSERT INTO `game`(`name`) VALUES ('狙击手：幽灵战士2');
INSERT INTO `game`(`name`) VALUES ('风向标');
INSERT INTO `game`(`name`) VALUES ('永生之境：吸血鬼战争');
INSERT INTO `game`(`name`) VALUES ('全面战争：三国');
INSERT INTO `game`(`name`) VALUES ('零：濡鸦之巫女');
INSERT INTO `game`(`name`) VALUES ('水晶危机');
INSERT INTO `game`(`name`) VALUES ('Jump大乱斗');
INSERT INTO `game`(`name`) VALUES ('热血无赖：终极版');
INSERT INTO `game`(`name`) VALUES ('控制/Control');
INSERT INTO `game`(`name`) VALUES ('英雄无敌3');
INSERT INTO `game`(`name`) VALUES ('Killsquad');
INSERT INTO `game`(`name`) VALUES ('MineRalph');
INSERT INTO `game`(`name`) VALUES ('钢铁雄心4');
INSERT INTO `game`(`name`) VALUES ('星露谷物语');
INSERT INTO `game`(`name`) VALUES ('荣誉勋章之空降神兵');
INSERT INTO `game`(`name`) VALUES ('火炬之光2');
INSERT INTO `game`(`name`) VALUES ('质量效应仙女座');
INSERT INTO `game`(`name`) VALUES ('');
INSERT INTO `game`(`name`) VALUES ('黑暗之魂3/2/1');
INSERT INTO `game`(`name`) VALUES ('乐高星球大战3');
INSERT INTO `game`(`name`) VALUES ('刀剑神域：失落之歌 黑衣剑士');
INSERT INTO `game`(`name`) VALUES ('正当防卫3');
INSERT INTO `game`(`name`) VALUES ('三国志10');
INSERT INTO `game`(`name`) VALUES ('鬼泣4特别版');
INSERT INTO `game`(`name`) VALUES ('英雄无敌6');
INSERT INTO `game`(`name`) VALUES ('国际足球大联盟17 FIFA 17');
INSERT INTO `game`(`name`) VALUES ('暗黑血统1-3');
INSERT INTO `game`(`name`) VALUES ('杀手4');
INSERT INTO `game`(`name`) VALUES ('魔道兵装');
INSERT INTO `game`(`name`) VALUES ('暴战机甲兵');
INSERT INTO `game`(`name`) VALUES ('海贼无双3');
INSERT INTO `game`(`name`) VALUES ('杀手2黄金版');
INSERT INTO `game`(`name`) VALUES ('薄暮传说：终极版');
INSERT INTO `game`(`name`) VALUES ('小小噩梦');
INSERT INTO `game`(`name`) VALUES ('V软模拟飞行10/PC微软模拟飞行10');
INSERT INTO `game`(`name`) VALUES ('失落余烬');
INSERT INTO `game`(`name`) VALUES ('末日准备狂');
INSERT INTO `game`(`name`) VALUES ('泰坦之旅：不朽王座');
INSERT INTO `game`(`name`) VALUES ('NBA 2K豪华版合集13-20代(2008-2019)');
INSERT INTO `game`(`name`) VALUES ('漩涡迷雾');
INSERT INTO `game`(`name`) VALUES ('装甲冲突3');
INSERT INTO `game`(`name`) VALUES ('职业篮球NBA18 NBA2K18');
INSERT INTO `game`(`name`) VALUES ('布莱尔女巫');
INSERT INTO `game`(`name`) VALUES ('母胎单身/Motesolo');
INSERT INTO `game`(`name`) VALUES ('仁王');
INSERT INTO `game`(`name`) VALUES ('狙击精英4/3/2/1/僵尸部队三部曲');
INSERT INTO `game`(`name`) VALUES ('使命召唤1');
INSERT INTO `game`(`name`) VALUES ('鬼谷八荒 v0.8.1008');
INSERT INTO `game`(`name`) VALUES ('求生之路1');
INSERT INTO `game`(`name`) VALUES ('风之旅人');
INSERT INTO `game`(`name`) VALUES ('荒野大镖客2：救赎/荒野大嫖客2：救赎');
INSERT INTO `game`(`name`) VALUES ('轩辕剑3：云和山的彼端');
INSERT INTO `game`(`name`) VALUES ('生化变种/BIOMUTANT');
INSERT INTO `game`(`name`) VALUES ('英雄无敌6');
INSERT INTO `game`(`name`) VALUES ('杀手5');
INSERT INTO `game`(`name`) VALUES ('怪物猎人：世界+冰原');
INSERT INTO `game`(`name`) VALUES ('暴力摩托2008');
INSERT INTO `game`(`name`) VALUES ('战斗砖块剧场/战斗方块剧场');
INSERT INTO `game`(`name`) VALUES ('古墓丽影暗影');
INSERT INTO `game`(`name`) VALUES ('警察模拟器：巡警');
INSERT INTO `game`(`name`) VALUES ('国际足球大联盟18 FIFA 18');
INSERT INTO `game`(`name`) VALUES ('天外世界/外部世界');
INSERT INTO `game`(`name`) VALUES ('帝国时代2：决定版 高清版');
INSERT INTO `game`(`name`) VALUES ('极品飞车5');
INSERT INTO `game`(`name`) VALUES ('正当防卫2');
INSERT INTO `game`(`name`) VALUES ('全面战争：战锤/战锤全面战争');
INSERT INTO `game`(`name`) VALUES ('杀手6');
INSERT INTO `game`(`name`) VALUES ('机甲战魔');
INSERT INTO `game`(`name`) VALUES ('河洛群侠传');
INSERT INTO `game`(`name`) VALUES ('讨鬼传2');
INSERT INTO `game`(`name`) VALUES ('最后纪元');
INSERT INTO `game`(`name`) VALUES ('荒野星球/星球流浪者');
INSERT INTO `game`(`name`) VALUES ('团队索尼克赛车/索尼克团队赛车/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('死亡之夜');
INSERT INTO `game`(`name`) VALUES ('刺客信条6枭雄');
INSERT INTO `game`(`name`) VALUES ('战地1');
INSERT INTO `game`(`name`) VALUES ('永远不再');
INSERT INTO `game`(`name`) VALUES ('凤凰点');
INSERT INTO `game`(`name`) VALUES ('流放者柯南');
INSERT INTO `game`(`name`) VALUES ('荒野大镖客：救赎1');
INSERT INTO `game`(`name`) VALUES ('废墟图书馆');
INSERT INTO `game`(`name`) VALUES ('怒之铁拳4/同屏联机');
INSERT INTO `game`(`name`) VALUES ('');
INSERT INTO `game`(`name`) VALUES ('蝙蝠侠：阿甘骑士/全系列');
INSERT INTO `game`(`name`) VALUES ('二之国：白色圣灰的女王重制版');
INSERT INTO `game`(`name`) VALUES ('乐高漫威超级英雄');
INSERT INTO `game`(`name`) VALUES ('死亡搁浅');
INSERT INTO `game`(`name`) VALUES ('血牌');
INSERT INTO `game`(`name`) VALUES ('世界汽车拉力锦标赛8/wrc8');
INSERT INTO `game`(`name`) VALUES ('秘境之柱');
INSERT INTO `game`(`name`) VALUES ('奥日和黑暗森林：终极版');
INSERT INTO `game`(`name`) VALUES ('只狼：影逝二度【1.05年度版】');
INSERT INTO `game`(`name`) VALUES ('血腥编年史：新的死亡循环');
INSERT INTO `game`(`name`) VALUES ('王国保卫战：起源【赠前线/皇家守卫军】');
INSERT INTO `game`(`name`) VALUES ('中世纪2：全面战争');
INSERT INTO `game`(`name`) VALUES ('重新计时/重组/重定/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('60秒重制版 60 Seconds! Reatomized');
INSERT INTO `game`(`name`) VALUES ('无线电指挥官');
INSERT INTO `game`(`name`) VALUES ('机器人殖民地');
INSERT INTO `game`(`name`) VALUES ('王权的陨落：巫师传说/巫师之昆特牌');
INSERT INTO `game`(`name`) VALUES ('突袭：二战');
INSERT INTO `game`(`name`) VALUES ('血根/Bloodroots');
INSERT INTO `game`(`name`) VALUES ('野性的海洋');
INSERT INTO `game`(`name`) VALUES ('战争之人：突击小队2 冷战');
INSERT INTO `game`(`name`) VALUES ('夜晚和白天');
INSERT INTO `game`(`name`) VALUES ('致命躯壳/Mortal Shell');
INSERT INTO `game`(`name`) VALUES ('古墓丽影1');
INSERT INTO `game`(`name`) VALUES ('黑相集：希望渺茫');
INSERT INTO `game`(`name`) VALUES ('刺客信条2兄弟会');
INSERT INTO `game`(`name`) VALUES ('帝国时代：终极版');
INSERT INTO `game`(`name`) VALUES ('方舟：生存进化');
INSERT INTO `game`(`name`) VALUES ('三国志12');
INSERT INTO `game`(`name`) VALUES ('乐高游戏系列');
INSERT INTO `game`(`name`) VALUES ('GTA5生化危机系列看门狗2等');
INSERT INTO `game`(`name`) VALUES ('剑与魂2：未见/刀剑与灵魂2尼弗森');
INSERT INTO `game`(`name`) VALUES ('红色警戒1+2+3win10版/红警3xp/win7版   局域网联机');
INSERT INTO `game`(`name`) VALUES ('孤岛危机2');
INSERT INTO `game`(`name`) VALUES ('拟真车祸模拟/BeamNG赛车');
INSERT INTO `game`(`name`) VALUES ('创世理想乡');
INSERT INTO `game`(`name`) VALUES ('侏罗纪世界：进化');
INSERT INTO `game`(`name`) VALUES ('统一指挥2');
INSERT INTO `game`(`name`) VALUES ('枪与香蕉');
INSERT INTO `game`(`name`) VALUES ('好雨之年');
INSERT INTO `game`(`name`) VALUES ('第二秒');
INSERT INTO `game`(`name`) VALUES ('文明6');
INSERT INTO `game`(`name`) VALUES ('逃离切尔诺贝利');
INSERT INTO `game`(`name`) VALUES ('耻辱2');
INSERT INTO `game`(`name`) VALUES ('光明记忆');
INSERT INTO `game`(`name`) VALUES ('鬼泣5/4/3/2/1/外传/特别版/7部合集');
INSERT INTO `game`(`name`) VALUES ('地球陨落/Earthfall');
INSERT INTO `game`(`name`) VALUES ('森特勒利亚');
INSERT INTO `game`(`name`) VALUES ('模拟人生4 全DLC版');
INSERT INTO `game`(`name`) VALUES ('乐高蝙蝠侠3');
INSERT INTO `game`(`name`) VALUES ('英雄无敌5');
INSERT INTO `game`(`name`) VALUES ('WWE2K18');
INSERT INTO `game`(`name`) VALUES ('义军');
INSERT INTO `game`(`name`) VALUES ('古墓丽影7');
INSERT INTO `game`(`name`) VALUES ('无尽宇宙/Neoverse');
INSERT INTO `game`(`name`) VALUES ('极品飞车15：变速');
INSERT INTO `game`(`name`) VALUES ('底特律变人/底特律：化身为人/底特律成为人类/');
INSERT INTO `game`(`name`) VALUES ('放逐之城');
INSERT INTO `game`(`name`) VALUES ('PC微软飞行模拟2020/PC微软模拟飞行202');
INSERT INTO `game`(`name`) VALUES ('刺客信条1-8包含奥德赛');
INSERT INTO `game`(`name`) VALUES ('流星蝴蝶剑');
INSERT INTO `game`(`name`) VALUES ('机甲战士5：雇佣兵');
INSERT INTO `game`(`name`) VALUES ('霓虹深渊/Neon Abyss');
INSERT INTO `game`(`name`) VALUES ('行尸走肉：生存本能');
INSERT INTO `game`(`name`) VALUES ('澳洲国际网球2/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('无主之地2');
INSERT INTO `game`(`name`) VALUES ('疯狂高楼大亨');
INSERT INTO `game`(`name`) VALUES ('银链');
INSERT INTO `game`(`name`) VALUES ('我的朋友佩德罗');
INSERT INTO `game`(`name`) VALUES ('极品飞车8');
INSERT INTO `game`(`name`) VALUES ('死侍');
INSERT INTO `game`(`name`) VALUES ('国土防线2：革命/1');
INSERT INTO `game`(`name`) VALUES ('战斗赛车');
INSERT INTO `game`(`name`) VALUES ('反恐精英 CS1.6+1.5');
INSERT INTO `game`(`name`) VALUES ('疑案追声');
INSERT INTO `game`(`name`) VALUES ('赛车计划3');
INSERT INTO `game`(`name`) VALUES ('最终幻想8：重制版/最终幻想8高清版');
INSERT INTO `game`(`name`) VALUES ('帝国：全面战争');
INSERT INTO `game`(`name`) VALUES ('光环：士官长合集/光环致远星');
INSERT INTO `game`(`name`) VALUES ('天国：拯救');
INSERT INTO `game`(`name`) VALUES ('甜蜜之家2+1/恐怖之家2+1');
INSERT INTO `game`(`name`) VALUES ('阿尔法行星/阿尔法星球');
INSERT INTO `game`(`name`) VALUES ('赛车计划1');
INSERT INTO `game`(`name`) VALUES ('逃出地牢/挺进地牢续作');
INSERT INTO `game`(`name`) VALUES ('山中凶宅');
INSERT INTO `game`(`name`) VALUES ('血战上海滩');
INSERT INTO `game`(`name`) VALUES ('孤岛危机1');
INSERT INTO `game`(`name`) VALUES ('海贼无双4');
INSERT INTO `game`(`name`) VALUES ('崩溃大陆');
INSERT INTO `game`(`name`) VALUES ('马场大亨8');
INSERT INTO `game`(`name`) VALUES ('罗马2：全面战争-帝皇版');
INSERT INTO `game`(`name`) VALUES ('地狱时刻');
INSERT INTO `game`(`name`) VALUES ('黑暗之魂2');
INSERT INTO `game`(`name`) VALUES ('石质碎片/Stoneshard');
INSERT INTO `game`(`name`) VALUES ('信长之野望13天道PK版');
INSERT INTO `game`(`name`) VALUES ('火影忍者忍者先锋');
INSERT INTO `game`(`name`) VALUES ('征服的荣耀：围城');
INSERT INTO `game`(`name`) VALUES ('缠结塔');
INSERT INTO `game`(`name`) VALUES ('黑水晶：抗战纪元战略版');
INSERT INTO `game`(`name`) VALUES ('美国逃亡者');
INSERT INTO `game`(`name`) VALUES ('开拓者：拥王者');
INSERT INTO `game`(`name`) VALUES ('腐烂国度2：巨霸主宰版');
INSERT INTO `game`(`name`) VALUES ('僵尸潮：灭绝');
INSERT INTO `game`(`name`) VALUES ('永恒之门');
INSERT INTO `game`(`name`) VALUES ('切尔诺贝利人');
INSERT INTO `game`(`name`) VALUES ('幸福工厂/满意工厂');
INSERT INTO `game`(`name`) VALUES ('毁灭战士4');
INSERT INTO `game`(`name`) VALUES ('量子破碎');
INSERT INTO `game`(`name`) VALUES ('模拟城市5未来之城');
INSERT INTO `game`(`name`) VALUES ('妖精的尾巴');
INSERT INTO `game`(`name`) VALUES ('旁观者2');
INSERT INTO `game`(`name`) VALUES ('边缘世界/环世界');
INSERT INTO `game`(`name`) VALUES ('生化危机1');
INSERT INTO `game`(`name`) VALUES ('如龙0');
INSERT INTO `game`(`name`) VALUES ('镜之边缘：催化剂—繁体中文版');
INSERT INTO `game`(`name`) VALUES ('舞华苍魔镜');
INSERT INTO `game`(`name`) VALUES ('龙珠：超宇宙/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('全面战争模拟器');
INSERT INTO `game`(`name`) VALUES ('要塞3');
INSERT INTO `game`(`name`) VALUES ('数码宝贝物语 网路侦探骇客追忆');
INSERT INTO `game`(`name`) VALUES ('荣誉勋章：先头部队');
INSERT INTO `game`(`name`) VALUES ('孤岛惊魂3');
INSERT INTO `game`(`name`) VALUES ('教父2');
INSERT INTO `game`(`name`) VALUES ('吃鸡模拟器/吃鸡教练');
INSERT INTO `game`(`name`) VALUES ('世界汽车拉力赛9');
INSERT INTO `game`(`name`) VALUES ('大逃杀大亨');
INSERT INTO `game`(`name`) VALUES ('哈迪斯：杀出地狱/地狱之战');
INSERT INTO `game`(`name`) VALUES ('战略思维：太平洋');
INSERT INTO `game`(`name`) VALUES ('辐射2');
INSERT INTO `game`(`name`) VALUES ('信长之野望14：创造威力加强版');
INSERT INTO `game`(`name`) VALUES ('职业篮球NBA15 NBA2K15');
INSERT INTO `game`(`name`) VALUES ('狙击手：幽灵战士契约');
INSERT INTO `game`(`name`) VALUES ('行尸走肉第三季');
INSERT INTO `game`(`name`) VALUES ('最终幻想10高清重制');
INSERT INTO `game`(`name`) VALUES ('钢铁之师2/钢铁雄狮2');
INSERT INTO `game`(`name`) VALUES ('骑马与砍杀：战团/骑砍1');
INSERT INTO `game`(`name`) VALUES ('绿色地狱');
INSERT INTO `game`(`name`) VALUES ('辐射4');
INSERT INTO `game`(`name`) VALUES ('要塞传奇');
INSERT INTO `game`(`name`) VALUES ('丧尸围城2-4（第4部不支持win7）');
INSERT INTO `game`(`name`) VALUES ('彩虹6号：围攻');
INSERT INTO `game`(`name`) VALUES ('疯狂的月亮');
INSERT INTO `game`(`name`) VALUES ('约会大作战：凛绪轮回HD');
INSERT INTO `game`(`name`) VALUES ('龙珠斗士Z/龙珠格斗Z/龙珠战士Z/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('进击的巨人');
INSERT INTO `game`(`name`) VALUES ('逃生1');
INSERT INTO `game`(`name`) VALUES ('动物园之星/Planet Zoo');
INSERT INTO `game`(`name`) VALUES ('ZAMB！无尽的毁灭');
INSERT INTO `game`(`name`) VALUES ('战纹/战律/火焰纹章+高级战争');
INSERT INTO `game`(`name`) VALUES ('职业篮球NBA2K20');
INSERT INTO `game`(`name`) VALUES ('孤岛惊魂5');
INSERT INTO `game`(`name`) VALUES ('以太新生');
INSERT INTO `game`(`name`) VALUES ('Weakless');
INSERT INTO `game`(`name`) VALUES ('模拟农场19');
INSERT INTO `game`(`name`) VALUES ('电脑装机模拟器');
INSERT INTO `game`(`name`) VALUES ('中世纪王朝');
INSERT INTO `game`(`name`) VALUES ('鬼泣5特别版');
INSERT INTO `game`(`name`) VALUES ('火影忍者3');
INSERT INTO `game`(`name`) VALUES ('伊拉图斯：死之主');
INSERT INTO `game`(`name`) VALUES ('质量效应（1-4）仙女座合集');
INSERT INTO `game`(`name`) VALUES ('街头力量足球');
INSERT INTO `game`(`name`) VALUES ('刺客信条大革命');
INSERT INTO `game`(`name`) VALUES ('狂战传说');
INSERT INTO `game`(`name`) VALUES ('真三国无双6');
INSERT INTO `game`(`name`) VALUES ('惊恐航海');
INSERT INTO `game`(`name`) VALUES ('三国志14');
INSERT INTO `game`(`name`) VALUES ('圣殿春秋');
INSERT INTO `game`(`name`) VALUES ('足球经理2019/2018');
INSERT INTO `game`(`name`) VALUES ('猎人：野性的呼唤/荒野的召唤');
INSERT INTO `game`(`name`) VALUES ('英雄连2');
INSERT INTO `game`(`name`) VALUES ('最终幻想15Q版');
INSERT INTO `game`(`name`) VALUES ('煮糊了2/分手厨房2/胡闹厨房2/地狱厨');
INSERT INTO `game`(`name`) VALUES ('鹰之岛');
INSERT INTO `game`(`name`) VALUES ('极品飞车21 热度');
INSERT INTO `game`(`name`) VALUES ('桥梁建造师2/Poly Bridge 2');
INSERT INTO `game`(`name`) VALUES ('魂斗罗：无赖军团【只支持手柄】');
INSERT INTO `game`(`name`) VALUES ('杀手1');
INSERT INTO `game`(`name`) VALUES ('地铁：2033');
INSERT INTO `game`(`name`) VALUES ('地铁离去/地铁离乡');
INSERT INTO `game`(`name`) VALUES ('玩具屋');
INSERT INTO `game`(`name`) VALUES ('轩辕剑4外传：苍之涛');
INSERT INTO `game`(`name`) VALUES ('吞食孔明传');
INSERT INTO `game`(`name`) VALUES ('泰坦陨落2');
INSERT INTO `game`(`name`) VALUES ('超级机器人大战V');
INSERT INTO `game`(`name`) VALUES ('WWE2K19');
INSERT INTO `game`(`name`) VALUES ('自动化餐厅');
INSERT INTO `game`(`name`) VALUES ('疯狂足球/Crazy Soccer');
INSERT INTO `game`(`name`) VALUES ('疯狂的麦克斯/Mad Max');
INSERT INTO `game`(`name`) VALUES ('漫漫长夜');
INSERT INTO `game`(`name`) VALUES ('真人快打X/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('南方公园：完整破碎/South Park: The Fractured But Whole');
INSERT INTO `game`(`name`) VALUES ('刀剑神域：虚空幻界');
INSERT INTO `game`(`name`) VALUES ('狂热运输2/疯狂运输2');
INSERT INTO `game`(`name`) VALUES ('丧尸围城3：天启版 v1.0.0.6');
INSERT INTO `game`(`name`) VALUES ('影子战术：将军之刃');
INSERT INTO `game`(`name`) VALUES ('SolSeraph');
INSERT INTO `game`(`name`) VALUES ('脱逃者2/逃脱者2/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('最终幻想世界');
INSERT INTO `game`(`name`) VALUES ('侍魂晓/新侍魂/侍魂晓:一决胜负/单机.同屏多人');
INSERT INTO `game`(`name`) VALUES ('使命召唤4现代战争 重置版');
INSERT INTO `game`(`name`) VALUES ('群星');
INSERT INTO `game`(`name`) VALUES ('正当防卫4');
INSERT INTO `game`(`name`) VALUES ('狙击精英4/Sniper Elite 4');
INSERT INTO `game`(`name`) VALUES ('NBA 2K20');
INSERT INTO `game`(`name`) VALUES ('美国卡车模拟');
INSERT INTO `game`(`name`) VALUES ('行尸走肉第一季');
INSERT INTO `game`(`name`) VALUES ('恶魔狩猎');
INSERT INTO `game`(`name`) VALUES ('最终幻想：零式HD');
INSERT INTO `game`(`name`) VALUES ('尘埃4/DiRT 4');
INSERT INTO `game`(`name`) VALUES ('奥日与鬼火意志/奥日与精灵意志/精灵与萤火意志');
INSERT INTO `game`(`name`) VALUES ('尸灵');
INSERT INTO `game`(`name`) VALUES ('天神镇');
INSERT INTO `game`(`name`) VALUES ('游戏目录');
INSERT INTO `game`(`name`) VALUES ('丧尸围城2');
INSERT INTO `game`(`name`) VALUES ('幽浮：奇美拉战队');
INSERT INTO `game`(`name`) VALUES ('尤卡莱莉与无妄巢穴');
INSERT INTO `game`(`name`) VALUES ('极品飞车16：亡命天涯');
INSERT INTO `game`(`name`) VALUES ('逆风停航');
INSERT INTO `game`(`name`) VALUES ('仙剑奇侠传3');
INSERT INTO `game`(`name`) VALUES ('嗜血印');
INSERT INTO `game`(`name`) VALUES ('刀剑神域：夺命凶弹');
INSERT INTO `game`(`name`) VALUES ('孤岛惊魂2');
INSERT INTO `game`(`name`) VALUES ('黑手党3');
INSERT INTO `game`(`name`) VALUES ('地铁：2033 重制版/Metro 2033 Redux');
INSERT INTO `game`(`name`) VALUES ('英雄无敌4');
INSERT INTO `game`(`name`) VALUES ('真三国无双5');
INSERT INTO `game`(`name`) VALUES ('乐高漫威超级英雄2');
INSERT INTO `game`(`name`) VALUES ('海岛大亨1-6');
INSERT INTO `game`(`name`) VALUES ('刺客信条1');
INSERT INTO `game`(`name`) VALUES ('鬼泣4');
INSERT INTO `game`(`name`) VALUES ('餐桌物语');
INSERT INTO `game`(`name`) VALUES ('自由人：游击战争');
INSERT INTO `game`(`name`) VALUES ('生化危机7 黄金版');
INSERT INTO `game`(`name`) VALUES ('巫师2：国王刺客增强版/巫师2刺客之王加强版');
INSERT INTO `game`(`name`) VALUES ('星际争霸2 自由之翼+虫群之心+虚空之遗+遭遇战破');
INSERT INTO `game`(`name`) VALUES ('言灵：藤泽七大秘密 英文版');
INSERT INTO `game`(`name`) VALUES ('小镇惊魂2');
INSERT INTO `game`(`name`) VALUES ('再见狂野之心');
INSERT INTO `game`(`name`) VALUES ('英雄连1');
INSERT INTO `game`(`name`) VALUES ('狙击手：幽灵战士1');
INSERT INTO `game`(`name`) VALUES ('刺客信条起源');
INSERT INTO `game`(`name`) VALUES ('饥荒');
INSERT INTO `game`(`name`) VALUES ('收获日2');
INSERT INTO `game`(`name`) VALUES ('文明6-3系列');
INSERT INTO `game`(`name`) VALUES ('真三国无双3-8');
INSERT INTO `game`(`name`) VALUES ('生化危机3');
INSERT INTO `game`(`name`) VALUES ('太空乱游');
INSERT INTO `game`(`name`) VALUES ('盟军敢死队2：高清重置版');
INSERT INTO `game`(`name`) VALUES ('行尸走肉：米琼恩');
INSERT INTO `game`(`name`) VALUES ('南瓜杰克');
INSERT INTO `game`(`name`) VALUES ('轩辕剑3外传：天之痕');
INSERT INTO `game`(`name`) VALUES ('战锤：混沌祸根');
INSERT INTO `game`(`name`) VALUES ('黑暗之魂3');
INSERT INTO `game`(`name`) VALUES ('刀剑神域：彼岸游境/Sword Art Online Alicization Lycoris');
INSERT INTO `game`(`name`) VALUES ('神奇蜘蛛侠2/超凡蜘蛛侠2+1+蜘蛛侠破碎维度');
INSERT INTO `game`(`name`) VALUES ('作业疯了');
INSERT INTO `game`(`name`) VALUES ('感染');
INSERT INTO `game`(`name`) VALUES ('德军总部3：新血脉');
INSERT INTO `game`(`name`) VALUES ('层层恐惧');
INSERT INTO `game`(`name`) VALUES ('螃蟹大战/单机.同屏多人.网络联机');
INSERT INTO `game`(`name`) VALUES ('魔界战记4+5');
INSERT INTO `game`(`name`) VALUES ('SD高达G世纪：火线纵横');
INSERT INTO `game`(`name`) VALUES ('进击的巨人2：最终之战');
INSERT INTO `game`(`name`) VALUES ('英雄不再：特拉维斯的反击');
INSERT INTO `game`(`name`) VALUES ('自动化帝国');
INSERT INTO `game`(`name`) VALUES ('帝国时代2');
INSERT INTO `game`(`name`) VALUES ('地球帝国3');
INSERT INTO `game`(`name`) VALUES ('古墓丽影9');
INSERT INTO `game`(`name`) VALUES ('巫师3：狂猎');
INSERT INTO `game`(`name`) VALUES ('仁王2');
INSERT INTO `game`(`name`) VALUES ('先祖：人类奥德赛');
INSERT INTO `game`(`name`) VALUES ('孤山速降/自行车速降');
INSERT INTO `game`(`name`) VALUES ('超级玛丽');
INSERT INTO `game`(`name`) VALUES ('开普勒斯');
INSERT INTO `game`(`name`) VALUES ('真人快打11');
INSERT INTO `game`(`name`) VALUES ('废土3');
INSERT INTO `game`(`name`) VALUES ('英雄传说：闪之轨迹3');
INSERT INTO `game`(`name`) VALUES ('杀手1-6   包含2黄金版');
INSERT INTO `game`(`name`) VALUES ('使命召唤14');
INSERT INTO `game`(`name`) VALUES ('魔铁危机/钢铁危机');
INSERT INTO `game`(`name`) VALUES ('莱莎的炼金工房：常暗的女王与秘密的隐居处');
INSERT INTO `game`(`name`) VALUES ('猎天使魔女2');

-- 开启自动提交
SET autocommit = 1;

-- 可以在mysql的配置文件my.ini中修改ngram的分词数（默认2），ngram_token_size=2

-- 创建全文索引
CREATE FULLTEXT INDEX ft_index ON game (name) WITH PARSER ngram;

-- 默认使用自然语言模式：IN NATURAL LANGUAGE MODE -- '刀剑危机'，分词结果：'刀剑'、'危机'
select name from game WHERE MATCH (name) AGAINST ('刀剑危机');


-- 使用布尔模式：IN BOOLEAN MODE，+和-操作符分别指示一个单词必须存在或不存在，才能进行匹配，'危机*'，则表示匹配危机开头的记录
select name from game WHERE MATCH (name) AGAINST ('+危机 -孤岛 -GTA' IN BOOLEAN MODE);