#端口
server:
  port: 8080
  servlet:
    context-path: /
management:
  endpoints:
    web:
      exposure:
        include=*:

spring:
  application:
    name: nova-log

  #SBA服务端地址
  boot:
    admin:
      client:
        url: http://localhost:8888

# log配置
logging:
  #可省略，springboot默认使用classpath下的logback-spring.xml作为日志配置文件，并且标准名称可支持springProperty
  config: classpath:log4j2-spring.xml
  #指定日志文件输出的目录路径。
  file:
    path: /Users/wangzehui/Documents/Logs/nova/${spring.application.name}