#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        max-active: 8
        max-wait: 3000
        max-idle: 8
        min-idle: 0
    timeout: 10000
