#端口
server:
  port: 8080
  servlet:
    context-path: /


rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: rocket-mq-producer
    send-message-timeout: 10000
  consumer:
    group: rocket-mq-consumer

