#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  # ========================== ↓↓↓↓↓↓ 邮件配置样例 ↓↓↓↓↓↓ ==========================
  mail:
    host: smtp.qq.com
    username: 1251850055@qq.com # TODO 账号
    password: uzalblzbzsmticah # TODO 注：这里填写 在邮箱 设置 -> 账号 里面生成的`授权码` !!!
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jasypt:
  encryptor:
    # 加密算法
    algorithm: PBEWITHHMACSHA512ANDAES_256
    # 加密使用的盐
    password: jaspyt_password
