#端口
server:
  port: 8080
  servlet:
    context-path: /

aliyun:
  oss:
    endpoint: oss-accelerate.aliyuncs.com
    accessKeyId: LTAI4G4id7xMN4FWbxoma
    accessKeySecret: 7ZMOPlFgQz6Ot1xrvKRlpl2Pt
    bucketName: excel