#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: nova-log-tlog

# log配置
logging:
  #可省略，springboot默认使用classpath下的logback-spring.xml作为日志配置文件，并且标准名称可支持springProperty
  config: classpath:logback-spring.xml
  #指定日志文件输出的目录路径。
  file:
    path: /Users/wangzehui/logs/nova/${spring.application.name}

# TLog配置
tlog:
  # 自动打印调用参数和时间
  enable-invoke-time-print: false
  # 打印上层服务名称、ip。[$preApp-上游微服务节点名称][$preHost-上游微服务的HostName][$preIp-上游微服务的IP地址][$spanId][$traceId]
  pattern: '[$traceId][$spanId]'