#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: local

  redis:
    host: 47.100.174.176
    port: 63799
    password: ENC(HfT5aVyvqAy4l4hfdoz6f1Ik+Pt7+d1A/XtxdfNv4oHMZsxUWvfFqAB0heosM8l4)
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 0
        max-wait: 3000
        time-between-eviction-runs: 50
    timeout: 1000

    sentinel: #高可用，主从模式
      master: master
      nodes: 127.0.0.1:26379

jasypt:
  encryptor:
    # 加密算法
    algorithm: PBEWITHHMACSHA512ANDAES_256
    # 加密使用的盐
    password: jaspyt_password