#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  redis:
    host: 47.100.174.176
    port: 63799
    password: '@wangzehui123'
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 3000
        time-between-eviction-runs: 50
    timeout: 1000

    sentinel: #高可用，主从模式
      master: master
      nodes: 127.0.0.1:26379