#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: nova-log-logback

# log配置
logging:
  #可省略，springboot默认使用classpath下的logback-spring.xml作为日志配置文件，并且标准名称可支持springProperty
  config: classpath:logback-spring.xml
  #指定日志文件输出的目录路径。
  file:
    path: /Users/wangzehui/logs/nova/${spring.application.name}