#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  data:
    mongodb:
      host: 47.100.174.176
      port: 27017
      username: root
      password: '@wangzehui123'
      authentication-database: admin  #认证的库
      database: myself    #操作的库
