#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  binlog4j:
    # redis配置信息
    redis-config:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 123456

    # mysql配置信息
    client-configs:
      master:
        host: 127.0.0.1
        port: 3306
        username: root
        password: 123456
        # 客户端编号
        serverId: 1990
        # 部署模式
        mode: standalone
        # 读取记忆
        persistence: true
        # 时区偏移量
        timeOffset: -28800000
