#端口
server:
  port: 8080
  servlet:
    context-path: /


#redis
redis:
  timeout: 6000ms
  password:
  cluster:
    max-redirects: 3  # 获取失败 最大重定向次数
    nodes:
      - redis1.cpnb.com:6379
      - redis2.cpnb.com:6379
      - redis3.cpnb.com:6379
  lettuce:
    pool:
      max-active: 100  #连接池最大连接数（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      min-idle: 5 # 连接池中的最小空闲连接
      max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
