#端口
server:
  port: 8080
  servlet:
    context-path: /

##德鲁伊连接池
spring:
  datasource:
    username: root
    password: ENC(HfT5aVyvqAy4l4hfdoz6f1Ik+Pt7+d1A/XtxdfNv4oHMZsxUWvfFqAB0heosM8l4)
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.174.176:3306/study?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8

  ##关闭spring启动图
  main:
    banner-mode: off

mybatis-plus:
  #关闭mybatis-plus启动图
  global-config:
    banner: false
  #打印log
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jasypt:
  encryptor:
    # 加密算法
    algorithm: PBEWITHHMACSHA512ANDAES_256
    # 加密使用的盐
    password: jaspyt_password