#端口
server:
  port: 8080
  servlet:
    context-path: /

#SBA监控客户端配置
management:
  endpoints:
    web:
      exposure:
        # 暴露所有端点
        include: "*"
    # 是否启用actuator，默认true
    enabled-by-default: true
  endpoint:
    health:
      # 健康检查显示详细信息（db，redis，diskSpace，ping...），默认never，只显示一个up
      show-details: always

spring:
  application:
    name: nova-tools
  jackson:
    ## 全局日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

    ## 时间戳（与上面互斥），但不能解决LocalDateTime转时间戳（JacksonCustomizerConfig类解决）
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

  #SBA服务端地址
  boot:
    admin:
      client:
        url: http://localhost:8888

  redis:
    # redis数据库索引（默认为0）
    database: 1
    # redis服务器地址
    host: 127.0.0.1
    # redis服务器连接端口
    port: 6379
    # redis服务器连接密码（尽量设置密码，防止远程注入服务器挖矿）
    password: 123456
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间
    timeout: 10000


  redis2:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: 3000
        max-idle: 8
        min-idle: 0
    timeout: 10000

  #mongo 配置信息
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
#      username: root
#      password: 123
      authentication-database: admin  #认证的库
      database: myself    #操作的库

#xxl:
#  job:
#    # 执行器通讯TOKEN [选填]：非空时启用；
#    accessToken: 8DCyt4wLgedT3YqVFAc1E8wkL1p4ykug
#    admin:
#      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
#      addresses: http://172.30.16.74:8080
#    executor:
#      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
#      address:
#      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
#      appname: tools-job
#      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
#      ip:
#      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
#      logpath: /opt/logbak/xxl-job/jobhandler
#      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
#      logretentiondays: 15
#      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
#      port: -1

jasypt:
  encryptor:
    # 加密算法
    algorithm: PBEWITHHMACSHA512ANDAES_256
    # 加密使用的盐
    password: jaspyt_password


# log配置
logging:
  file:
    path: /Users/wangzehui/logs/nova/${spring.application.name}

# @value如何获取hashMap结构数据
test:
  map: '{"test1":"12345","test2":"54321"}'

