#端口
server:
  port: 8080
  servlet:
    context-path: /

#多数据源
mybatis-flex:
  global-config:
    #关闭logo
    print-banner: false
  datasource:
    master:
      type: druid
      url: jdbc:mysql://47.100.174.176:3306/study?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: ENC(HfT5aVyvqAy4l4hfdoz6f1Ik+Pt7+d1A/XtxdfNv4oHMZsxUWvfFqAB0heosM8l4)
      driver-class-name: com.mysql.cj.jdbc.Driver
    my_mall:
      type: druid
      url: jdbc:mysql://47.100.174.176:3306/my_mall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: ENC(HfT5aVyvqAy4l4hfdoz6f1Ik+Pt7+d1A/XtxdfNv4oHMZsxUWvfFqAB0heosM8l4)
      driver-class-name: com.mysql.cj.jdbc.Driver


jasypt:
  encryptor:
    # 加密算法
    algorithm: PBEWITHHMACSHA512ANDAES_256
    # 加密使用的盐
    password: jaspyt_password