#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  data:
    solr:
      host: http://username:password@ip:port/xxx

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: jaspyt_password

