#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  redis:
    # redis数据库索引（默认为0）
    database: 0
    # redis服务器地址
    host: 47.100.174.176
    # redis服务器连接端口
    port: 63799
    # redis服务器连接密码（尽量设置密码，防止远程注入服务器挖矿）
    password: ENC(HfT5aVyvqAy4l4hfdoz6f1Ik+Pt7+d1A/XtxdfNv4oHMZsxUWvfFqAB0heosM8l4)
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接超时时间
    timeout: 10000


#caffeine 本地缓存配置
caffeine:
  cacheNames: caffeine
  initCapacity: 100
  maxSize: 1000
  expireAfterAccess: 600

jasypt:
  encryptor:
    # 加密算法
    algorithm: PBEWITHHMACSHA512ANDAES_256
    # 加密使用的盐
    password: jaspyt_password