#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  elasticsearch:
    uris: http://225297c275c2.c.methodot.com

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: jaspyt_password