#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  elasticsearch:
    uris: http://101.201.74.5:9201

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: jaspyt_password