#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  elasticsearch:
    uris: ENC(kydBwmksW8ubJonzgxrdvCXsRKP2r0QDbwQz39EsfPrj5X3xcto/hyAC7gU1D3Q7n8YaqhdF3zjRPDNxfwYoyw==)
    #超时时间，单位：秒
    connection-timeout: 1000

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: jaspyt_password