#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  redis:
    # 自定义参数
    address: 127.0.0.1:6379
    type: SINGLE
    password: 123456
    database: 0

    # redis服务器地址
    host: 127.0.0.1
    # redis服务器连接端口
    port: 6379

