#端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  redis:
    # 自定义参数
    address: 127.0.0.1:6379
    type: standalone

    # redis服务器地址
    host: 127.0.0.1
    # redis服务器连接端口
    port: 6379
#    password: ENC(HfT5aVyvqAy4l4hfdoz6f1Ik+Pt7+d1A/XtxdfNv4oHMZsxUWvfFqAB0heosM8l4)
    database: 0

